apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-service
  namespace: ingress-nginx
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '10254'
spec:
  type: ClusterIP
  selector:
    name: nginx-ingress-controller
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
